@Demo_01_HostAddress = http://localhost:5175

### 测试聊天接口 - 非流式
GET {{Demo_01_HostAddress}}/api/chat/v1/normalchat?message=什么是deepseek

###

### 测试聊天接口 - 流式
GET {{Demo_01_HostAddress}}/api/chat/v1/streamchat?message=什么是deepseek

###
